[tool.ruff]
line-length = 120
lint.select = ["E", "W", "F", "I", "C"]
lint.ignore = ["E501"]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "lf"

[lint.tool.ruff]
# Enable Pyflakes, Pycodestyle, isort
lint.select = ["E", "W", "F", "I", "C", "UP", "B", "A", "SIM", "TID", "ARG", "RUF"]
lint.ignore = [
    "E501", # line too long, handled by formatter
]

[tool.ruff.lint.isort]
known-first-party = ["backend"]

[tool.ruff.lint.flake8-import-conventions]
aliases = { boto3 = "boto" }

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-ra -q --cov=backend --cov-report=html --cov-report=xml"
testpaths = [
    "tests",
]
python_files = "test_*.py"
python_classes = "Test*"
python_functions = "test_*"
# Filter out warnings from dependencies if necessary
# filterwarnings = [
# "ignore::DeprecationWarning:pydantic.*:",
# ]
