AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  kids-rewards-backend

Globals:
  Function:
    Timeout: 30
    MemorySize: 128

Parameters:
  TableNamePrefix:
    Type: String
    Description: Prefix for DynamoDB table names (e.g., dev-, staging-, prod-)
    Default: ''
  AppImageUri:
    Type: String
    Description: The ECR URI of the Docker image for the Lambda function.
  LocalDynamoDBEndpoint: # Moved from later in the file
    Type: String
    Description: Local DynamoDB endpoint (e.g., http://localhost:8000)
    Default: "" # Default to empty string, indicating not a local environment
  AppSecret:
    Type: String
    Description: The secret key for the application. Must be at least 32 characters long.
    Default: ""

Resources:
  KidsRewardsLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      ImageUri: !Ref AppImageUri
      Architectures:
        - x86_64
      Events:
        Api:
          Type: Api
          Properties:
            Path: /{proxy+} # Define a proxy path event
            Method: any
            # Cors block removed to delegate CORS handling to the FastAPI application
      Environment:
        Variables:
          DYNAMODB_ENDPOINT_OVERRIDE: !If [IsLocalEnvironment, !Ref LocalDynamoDBEndpoint, !Ref "AWS::NoValue"] # Use local endpoint if parameter is provided
          USERS_TABLE_NAME: !If [IsLocalEnvironment, "KidsRewardsUsers", !Sub "${TableNamePrefix}KidsRewardsUsers"]
          STORE_ITEMS_TABLE_NAME: !If [IsLocalEnvironment, "KidsRewardsStoreItems", !Sub "${TableNamePrefix}KidsRewardsStoreItems"]
          PURCHASE_LOGS_TABLE_NAME: !If [IsLocalEnvironment, "KidsRewardsPurchaseLogs", !Sub "${TableNamePrefix}KidsRewardsPurchaseLogs"]
          APP_SECRET_KEY: !Ref AppSecret
      Policies: # Corrected indentation for the Policies key
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - arn:aws:iam::aws:policy/AmazonDynamoDBFullAccess
    Metadata: 
      Dockerfile: Dockerfile  
      DockerContext: . 
      DockerTag: latest       
  KidsRewardsTable: # New DynamoDB Table Resource
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !If [IsLocalEnvironment, "KidsRewardsUsers", !Sub "${TableNamePrefix}KidsRewardsUsers"]
      AttributeDefinitions:
        - AttributeName: username
          AttributeType: S
      KeySchema:
        - AttributeName: username
          KeyType: HASH
      ProvisionedThroughput: # Or use OnDemandThroughput
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
    DeletionPolicy: Retain

  KidsRewardsStoreItemsTable: # New DynamoDB Table Resource for Store Items
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !If [IsLocalEnvironment, "KidsRewardsStoreItems", !Sub "${TableNamePrefix}KidsRewardsStoreItems"]
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S # Assuming id is a string, adjust if needed
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      ProvisionedThroughput: # Or use OnDemandThroughput
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
    DeletionPolicy: Retain

  KidsRewardsPurchaseLogsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !If [IsLocalEnvironment, "KidsRewardsPurchaseLogs", !Sub "${TableNamePrefix}KidsRewardsPurchaseLogs"]
      AttributeDefinitions:
        - AttributeName: id # Primary Key
          AttributeType: S
        - AttributeName: user_id # For GSI UserIdTimestampIndex
          AttributeType: S
        - AttributeName: timestamp # For GSIs (Range Key)
          AttributeType: S # Timestamps stored as ISO strings
        - AttributeName: status    # For GSI StatusTimestampIndex
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      GlobalSecondaryIndexes:
        - IndexName: UserIdTimestampIndex
          KeySchema:
            - AttributeName: user_id
              KeyType: HASH
            - AttributeName: timestamp
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: 5
            WriteCapacityUnits: 5
        - IndexName: StatusTimestampIndex
          KeySchema:
            - AttributeName: status
              KeyType: HASH
            - AttributeName: timestamp
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: 5
            WriteCapacityUnits: 5
    DeletionPolicy: Retain

Conditions:
  IsLocalEnvironment: !Not [!Equals [!Ref LocalDynamoDBEndpoint, ""]] # Condition to check if local endpoint is provided

Outputs:
  KidsRewardsApi:
    Description: "API Gateway endpoint URL for Prod stage for Kids Rewards function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
  KidsRewardsLambdaFunction:
    Description: "Kids Rewards Lambda Function ARN"
    Value: !GetAtt KidsRewardsLambdaFunction.Arn
  KidsRewardsLambdaFunctionIamRole:
    Description: "Implicit IAM Role created for Kids Rewards function"
    Value: !GetAtt KidsRewardsLambdaFunctionRole.Arn