AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  kids-rewards-backend

Globals:
  Function:
    Timeout: 30
    MemorySize: 128

Parameters:
  TableNamePrefix:
    Type: String
    Description: Prefix for DynamoDB table names (e.g., dev-, staging-, prod-)
    Default: ''
  AppImageUri:
    Type: String
    Description: The ECR URI of the Docker image for the Lambda function.
  LocalDynamoDBEndpoint:
    Type: String
    Description: Local DynamoDB endpoint (e.g., http://localhost:8000)
    Default: ""
  AppSecret:
    Type: String
    Description: The secret key for the application. Must be at least 32 characters long.
    Default: ""

Resources:
  KidsRewardsLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      ImageUri: !Ref AppImageUri
      Architectures:
        - x86_64
      Events:
        Api:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: any
      Environment:
        Variables:
          DYNAMODB_ENDPOINT_OVERRIDE: !If [IsLocalEnvironment, !Ref LocalDynamoDBEndpoint, !Ref "AWS::NoValue"]
          USERS_TABLE_NAME: !If [IsLocalEnvironment, "KidsRewardsUsers", !Sub "${TableNamePrefix}KidsRewardsUsers"]
          STORE_ITEMS_TABLE_NAME: !If [IsLocalEnvironment, "KidsRewardsStoreItems", !Sub "${TableNamePrefix}KidsRewardsStoreItems"]
          PURCHASE_LOGS_TABLE_NAME: !If [IsLocalEnvironment, "KidsRewardsPurchaseLogs", !Sub "${TableNamePrefix}KidsRewardsPurchaseLogs"]
          CHORES_TABLE_NAME: !If [IsLocalEnvironment, "KidsRewardsChores", !Sub "${TableNamePrefix}KidsRewardsChores"]
          CHORE_LOGS_TABLE_NAME: !If [IsLocalEnvironment, "KidsRewardsChoreLogs", !Sub "${TableNamePrefix}KidsRewardsChoreLogs"]
          REQUESTS_TABLE_NAME: !If [IsLocalEnvironment, "KidsRewardsRequests", !Sub "${TableNamePrefix}KidsRewardsRequests"] # New Table Env Var
          APP_SECRET_KEY: !Ref AppSecret
      Policies:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - arn:aws:iam::aws:policy/AmazonDynamoDBFullAccess
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: .
      DockerTag: latest

  KidsRewardsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !If [IsLocalEnvironment, "KidsRewardsUsers", !Sub "${TableNamePrefix}KidsRewardsUsers"]
      AttributeDefinitions:
        - AttributeName: username
          AttributeType: S
      KeySchema:
        - AttributeName: username
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
    DeletionPolicy: Retain

  KidsRewardsStoreItemsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !If [IsLocalEnvironment, "KidsRewardsStoreItems", !Sub "${TableNamePrefix}KidsRewardsStoreItems"]
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
    DeletionPolicy: Retain

  KidsRewardsPurchaseLogsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !If [IsLocalEnvironment, "KidsRewardsPurchaseLogs", !Sub "${TableNamePrefix}KidsRewardsPurchaseLogs"]
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: user_id
          AttributeType: S
        - AttributeName: timestamp
          AttributeType: S
        - AttributeName: status
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      GlobalSecondaryIndexes:
        - IndexName: UserIdTimestampIndex
          KeySchema:
            - AttributeName: user_id
              KeyType: HASH
            - AttributeName: timestamp
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: 5
            WriteCapacityUnits: 5
        - IndexName: StatusTimestampIndex
          KeySchema:
            - AttributeName: status
              KeyType: HASH
            - AttributeName: timestamp
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: 5
            WriteCapacityUnits: 5
    DeletionPolicy: Retain

  KidsRewardsChoresTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !If [IsLocalEnvironment, "KidsRewardsChores", !Sub "${TableNamePrefix}KidsRewardsChores"]
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: created_by_parent_id
          AttributeType: S
        - AttributeName: is_active
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      GlobalSecondaryIndexes:
        - IndexName: ParentChoresIndex
          KeySchema:
            - AttributeName: created_by_parent_id
              KeyType: HASH
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: 2
            WriteCapacityUnits: 2
        - IndexName: ActiveChoresIndex
          KeySchema:
            - AttributeName: is_active
              KeyType: HASH
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: 2
            WriteCapacityUnits: 2
    DeletionPolicy: Retain

  KidsRewardsChoreLogsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !If [IsLocalEnvironment, "KidsRewardsChoreLogs", !Sub "${TableNamePrefix}KidsRewardsChoreLogs"]
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: kid_id
          AttributeType: S
        - AttributeName: submitted_at
          AttributeType: S
        - AttributeName: status
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      GlobalSecondaryIndexes:
        - IndexName: KidChoreLogIndex
          KeySchema:
            - AttributeName: kid_id
              KeyType: HASH
            - AttributeName: submitted_at
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: 2
            WriteCapacityUnits: 2
        - IndexName: ChoreLogStatusIndex
          KeySchema:
            - AttributeName: status
              KeyType: HASH
            - AttributeName: submitted_at
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: 2
            WriteCapacityUnits: 2
    DeletionPolicy: Retain

  KidsRewardsRequestsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !If [IsLocalEnvironment, "KidsRewardsRequests", !Sub "${TableNamePrefix}KidsRewardsRequests"]
      AttributeDefinitions:
        - AttributeName: id # Primary Key
          AttributeType: S
        - AttributeName: requester_id # For GSI
          AttributeType: S
        - AttributeName: created_at # For GSI sort key
          AttributeType: S
        - AttributeName: status # For GSI
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      GlobalSecondaryIndexes:
        - IndexName: RequesterIdCreatedAtGSI
          KeySchema:
            - AttributeName: requester_id
              KeyType: HASH
            - AttributeName: created_at
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: 2
            WriteCapacityUnits: 2
        - IndexName: StatusCreatedAtGSI
          KeySchema:
            - AttributeName: status
              KeyType: HASH
            - AttributeName: created_at
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: 2
            WriteCapacityUnits: 2
    DeletionPolicy: Retain

Conditions:
  IsLocalEnvironment: !Not [!Equals [!Ref LocalDynamoDBEndpoint, ""]]

Outputs:
  KidsRewardsApi:
    Description: "API Gateway endpoint URL for Prod stage for Kids Rewards function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
  KidsRewardsLambdaFunction:
    Description: "Kids Rewards Lambda Function ARN"
    Value: !GetAtt KidsRewardsLambdaFunction.Arn
  KidsRewardsLambdaFunctionIamRole:
    Description: "Implicit IAM Role created for Kids Rewards function"
    Value: !GetAtt KidsRewardsLambdaFunctionRole.Arn