name: Teardown Staging Backend

on:
  pull_request:
    types: [closed]
    branches:
      - main
      - develop
  delete:

jobs:
  teardown:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Get branch name slug
        id: get_branch_slug
        run: |
          # Get branch name from pull request head ref or deleted branch ref
          BRANCH_NAME=$(echo "${{ github.event.pull_request.head.ref || github.event.ref }}" | sed 's/refs\/heads\///' | sed 's/[^a-zA-Z0-9]/-/g' | tr '[:upper:]' '[:lower:]')
          echo "BRANCH_SLUG=$BRANCH_NAME" >> $GITHUB_OUTPUT

      - name: Delete SAM stack
        run: |
          STACK_NAME="kids-rewards-staging-${{ steps.get_branch_slug.outputs.BRANCH_SLUG }}"
          echo "Attempting to delete stack: $STACK_NAME"
          aws cloudformation delete-stack --stack-name $STACK_NAME
          # Optionally wait for stack deletion to complete
          # aws cloudformation wait stack-delete-complete --stack-name $STACK_NAME
        env:
          AWS_PAGER: '' # Disable AWS CLI pager